export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const EMPTY_USERS_LIST = 'EMPTY_USERS_LIST';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';

export const CHANGE_SORTING_ORDER = 'CHANGE_SORTING_ORDER';
